//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warsztat
{
    using System;
    using System.Collections.Generic;
    
    public partial class czynnosci_naprawcze
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public czynnosci_naprawcze()
        {
            this.mechanicy = new HashSet<mechanicy>();
        }
    
        public int idCzynnosci { get; set; }
        public Nullable<decimal> cena { get; set; }
        public string opis { get; set; }
        public int idNaprawy { get; set; }
        public int idCennik { get; set; }
    
        public virtual cennik cennik { get; set; }
        public virtual naprawy naprawy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mechanicy> mechanicy { get; set; }
    }
}
