//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warsztat
{
    using System;
    using System.Collections.Generic;
    
    public partial class dane_kontaktowe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dane_kontaktowe()
        {
            this.klienci = new HashSet<klienci>();
            this.mechanicy = new HashSet<mechanicy>();
        }
    
        public int idDane { get; set; }
        public string nr_telefonu { get; set; }
        public string miejscowosc { get; set; }
        public string ulica { get; set; }
        public string numer { get; set; }
        public string kod_pocztowy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<klienci> klienci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mechanicy> mechanicy { get; set; }
    }
}
