//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warsztat
{
    using System;
    using System.Collections.Generic;
    
    public partial class samochody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public samochody()
        {
            this.naprawy = new HashSet<naprawy>();
        }
    
        public int idSamochodu { get; set; }
        public string VIN { get; set; }
        public string marka { get; set; }
        public string model { get; set; }

        public string nr_rejestracji { get; set; }
        public int idKlienta { get; set; }
    
        internal virtual klienci klienci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<naprawy> naprawy { get; set; }
    }
}
